version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-local
    image: rabbitmq:latest

  mysql:
    container_name: mysql-local
    image: mysql:latest
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: sword
      MYSQL_ROOT_PASSWORD: 1234

  backend:
    container_name: backend-local
    build:
      dockerfile: Dockerfile
    image: mybackend-built-image
    depends_on:
      - rabbitmq
      - mysql
    ports:
    - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: mysql
      DB_PORT: 3306
      DB_PASSWORD: 1234
      RABBITMQ_HOST: rabbitmq
      DB_MIGRATE: "true"
      DB_MIGRATE_RETRIES: 20
      DB_MIGRATE_WAIT_TIME: 3
